variables:
  USER: "mirhamedjz"
  PASSWORD: "MirHamed2495"
  IMAGE_BACKEND: "mirhamedjz/loghme-backend"
  IMAGE_DB: "mirhamedjz/loghme-db"
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$USER" -p "$PASSWORD"
  script:
    - docker build --pull -t "$IMAGE_BACKEND" .
    - docker push "$IMAGE_BACKEND"
    - docker build --pull -t "$IMAGE_DB" ./src/main/resources/Loghme-DB
    - docker push "$IMAGE_DB"
  after_script:
    - docker logout
  only:
    - master