variables:
  USER: "mirhamedjz"
  PASSWORD: "MirHamed2495"
  IMAGE: "mirhamedjz/loghme-backend"
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$USER" -p "$PASSWORD"
  script:
    - docker build --pull -t "$IMAGE" .
    - docker push "$IMAGE"
  after_script:
    - docker logout
  only:
    - master