apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: loghme-db
spec:
  selector:
    matchLabels:
      app: loghme-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loghme-db
    spec:
      containers:
      - name: loghme-db
        image: mirhamedjz/loghme-db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MirHamed2495
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.4"
          requests:
            memory: "350Mi"
            cpu: "0.2"
        ports:
        - containerPort: 3306
          name: loghme-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: tz-config
          mountPath: /etc/localtime
        args:
          - --character-set-server=utf8
          - --collation-server=utf8_general_ci
          - --skip-character-set-client-handshake
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Tehran
          type: File